# Generated by Django 4.2.5 on 2023-09-19 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("LearningResource", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submodule",
            name="parent_module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_modules",
                to="LearningResource.learningmodule",
            ),
        ),
    ]
