# Generated by Django 4.2.5 on 2023-09-19 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("LearningResource", "0002_alter_submodule_parent_module"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningmodule",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="submodule",
            name="parent_module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_modules",
                to="LearningResource.learningmodule",
            ),
        ),
    ]
