# Generated by Django 4.2.5 on 2023-09-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LearningResource", "0004_learningmodule_short_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningmodule",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
