# Generated by Django 4.2.5 on 2023-09-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LearningResource", "0005_alter_learningmodule_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videotutorial",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="videotutorial",
            name="subtitles",
        ),
        migrations.RemoveField(
            model_name="videotutorial",
            name="video_url",
        ),
        migrations.AddField(
            model_name="videotutorial",
            name="name",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="videotutorial",
            name="video_id",
            field=models.CharField(max_length=11, null=True),
        ),
    ]
