# Generated by Django 4.2.5 on 2023-09-19 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("LearningResource", "0006_remove_videotutorial_duration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submodule",
            name="video",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="LearningResource.videotutorial",
            ),
        ),
    ]
