# Generated by Django 4.2.5 on 2023-09-20 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("LearningResource", "0007_submodule_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="submodule",
            name="next_submodule",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="next_module",
                to="LearningResource.submodule",
            ),
        ),
        migrations.AddField(
            model_name="submodule",
            name="prev_submodule",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prev_module",
                to="LearningResource.submodule",
            ),
        ),
    ]
