# Generated by Django 4.2.5 on 2023-09-20 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("LearningResource", "0008_submodule_next_submodule_submodule_prev_submodule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submodule",
            name="next_submodule",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="next_lecture",
                to="LearningResource.submodule",
            ),
        ),
        migrations.AlterField(
            model_name="submodule",
            name="prev_submodule",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prev_lecture",
                to="LearningResource.submodule",
            ),
        ),
    ]
