# Generated by Django 4.2.5 on 2023-10-14 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LearningResource", "0009_alter_submodule_next_submodule_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Challenge",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
        migrations.DeleteModel(
            name="Quiz",
        ),
    ]
