# Generated by Django 4.2.5 on 2023-10-19 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("LearningResource", "0010_delete_challenge_delete_question_delete_quiz"),
        ("UserManagement", "0004_remove_progresstracker_badges_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgressTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("overall_progres", models.FloatField(default=0.0)),
                ("badges", models.ManyToManyField(to="LearningResource.badge")),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UserManagement.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModuleProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("progress", models.FloatField(default=0.0)),
                (
                    "completed_submodules",
                    models.ManyToManyField(to="LearningResource.submodule"),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_progress",
                        to="LearningResource.learningmodule",
                    ),
                ),
                (
                    "progress_tracker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_progress",
                        to="ProgressTracker.progresstracker",
                    ),
                ),
            ],
        ),
    ]
