# Generated by Django 4.2.5 on 2023-10-20 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ProgressTracker", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="progresstracker",
            old_name="overall_progres",
            new_name="overall_progress",
        ),
    ]
