# Generated by Django 4.2.5 on 2023-09-19 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("LearningResource", "0001_initial"),
        ("UserManagement", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parent",
            name="number_of_children",
        ),
        migrations.RemoveField(
            model_name="student",
            name="enrollment_date",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="subject",
        ),
        migrations.AddField(
            model_name="student",
            name="birthday",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="coding_experience",
            field=models.CharField(
                choices=[
                    ("No experience", "No experience"),
                    ("Little experience", "Little experience"),
                    ("Comfortable", "Comfortable"),
                ],
                default="No experience",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="UserManagement.parent",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="parent_email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="course",
            field=models.ManyToManyField(to="LearningResource.submodule"),
        ),
        migrations.CreateModel(
            name="ProgressTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("overall_progress_bar", models.FloatField(default=0.0)),
                ("badges", models.ManyToManyField(to="LearningResource.badge")),
                (
                    "completed_modules",
                    models.ManyToManyField(to="LearningResource.submodule"),
                ),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UserManagement.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModuleProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("progress_bar", models.FloatField(default=0.0)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_progress",
                        to="LearningResource.submodule",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="UserManagement.student",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="student",
            name="module_progress",
            field=models.ManyToManyField(
                related_name="students", to="UserManagement.moduleprogress"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="progress_tracker",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_entry",
                to="UserManagement.progresstracker",
            ),
        ),
    ]
