# Generated by Django 4.2.5 on 2023-09-23 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserManagement", "0002_remove_parent_number_of_children_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parent",
            name="profile_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="student",
            name="profile_completed",
            field=models.BooleanField(default=False),
        ),
    ]
