# Generated by Django 4.2.5 on 2023-10-19 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("UserManagement", "0003_parent_profile_completed_student_profile_completed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="progresstracker",
            name="badges",
        ),
        migrations.RemoveField(
            model_name="progresstracker",
            name="completed_modules",
        ),
        migrations.RemoveField(
            model_name="progresstracker",
            name="student",
        ),
        migrations.RemoveField(
            model_name="student",
            name="module_progress",
        ),
        migrations.RemoveField(
            model_name="student",
            name="progress_tracker",
        ),
        migrations.DeleteModel(
            name="ModuleProgress",
        ),
        migrations.DeleteModel(
            name="ProgressTracker",
        ),
    ]
