# Generated by Django 4.2.6 on 2023-10-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LearningResource", "0011_learningmodule_thumbnail"),
        ("UserManagement", "0004_remove_progresstracker_badges_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="course",
            field=models.ManyToManyField(to="LearningResource.learningmodule"),
        ),
    ]
