# Generated by Django 4.2.5 on 2023-10-14 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("QuizChallengeSystem", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="choices",
        ),
        migrations.RemoveField(
            model_name="question",
            name="correct_answer",
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="QuizChallengeSystem.question",
                    ),
                ),
            ],
        ),
    ]
