# Generated by Django 4.2.5 on 2023-10-14 15:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("UserManagement", "0003_parent_profile_completed_student_profile_completed"),
        ("QuizChallengeSystem", "0002_remove_question_choices_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useranswer",
            name="timestamp",
        ),
        migrations.RemoveField(
            model_name="useranswer",
            name="user",
        ),
        migrations.CreateModel(
            name="QuizResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("score", models.IntegerField()),
                ("total_questions", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="QuizChallengeSystem.quiz",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UserManagement.student",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="useranswer",
            name="quiz_result",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_answers",
                to="QuizChallengeSystem.quizresult",
            ),
        ),
    ]
