# Generated by Django 4.2.6 on 2023-10-26 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LearningResource', '0011_learningmodule_thumbnail'),
        ('QuizChallengeSystem', '0003_remove_useranswer_timestamp_remove_useranswer_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='sub_module',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='LearningResource.submodule'),
        ),
    ]
