# Generated by Django 4.2.6 on 2023-10-30 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("QuizChallengeSystem", "0004_quiz_sub_module"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="expected_output",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="challenge",
            name="std_in",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="hints",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="quizresult",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quiz_result",
                to="QuizChallengeSystem.quiz",
            ),
        ),
    ]
