# Generated by Django 4.2.6 on 2023-10-30 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "QuizChallengeSystem",
            "0005_challenge_expected_output_challenge_std_in_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="sample_output",
            field=models.TextField(blank=True, null=True),
        ),
    ]
